// Textos sobre como va la historia del juego//

//"El diario a diario"

 //Un señor compra un diario
//Toma un tranvia y cuando desciende 
//Deja el diario en
//un banco de un plaza                                           
//se lo olvida en el tranvia
//El diario se convierte en un monton de hojas impresas
//un muchacho lo ve...
//un estudiante de arte lo agarra...
//Lo lee y se convierte en un diario
//Y usa el diario para
//cubrir el piso para ...
//hacer una cartapesta para...
//no ensuciar el piso mientras pinta el mural
//terminar su escultura
//y venderla en la estacion de tranvias
//Luego deja el diario en un banco de la plaza y se convierte en
//un monton de ...
//un origami de...
//¡HOJAS IMPRESAS!
//¡GRULLA!
//Una anciana lo ve, lo lee y se convierte en un diario...
//UN DIARIO
//Luego lo deja en el banco de la plaza, 
//el diario se convierte en...
//un barquito de...
//¡PAPEL!
//La anciana lo agarra...
//Un nene lo agarra y...
//Se lo lleva a su casa
//y en el camino lo usa para
//empaquetar ...
//empezar un fuego para...
//Medio kilo de acelga
//Hacer un asado
//Lo usa para...
//convertirlo en un...
//ponerselo en la cabeza y...
//¡AVION DE PAPEL!
//Se transforma en ¡UN SOMBRERO!
//Que es para eso que sirven los diarios 
//Despues de tantas metarmofosis//
